server:
  port: 8080
  servlet:
    context-path: /personalog

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
  mail:
    host: 127.0.0.1
    port: 1025
#    username:
#    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
